### ISSUE TITLE
The shortcut Ctrl+C does not work on replay.

### ISSUE THREAD

**Issue by loicmorvan** [xps/VSTextMacros#15] opened 2016-04-18 13:06 UTC
It used to work some months ago but now the text is not copied to the clipboard when Ctrl+C is executed.

Note that Ctrl+V does work but pastes the previous Ctrl+C made by the user, not the one from the recorded macro.

**Comment by xps** [comment] 2016-05-04 14:54
Hi Loïc, and thanks for reporting this.

I think this is a duplicate of [this issue](https://github.com/xps/VSTextMacros/issues/14), so I will close accordingly. 

Please check the discussion there, you will find reproduction steps to confirm the problem, as well as a mention to Productivity Power Tools 2015 that may cause the problem. If you have any additional info, feel free to add it there.

**Closed by xps** 2016-05-04 14:54 UTC
