### ISSUE TITLE
Allow a keyboard shortcut to be assigned to a saved macro

### ISSUE THREAD

**Issue by rusql** [xps/VSTextMacros#19] opened 2016-06-05 11:11 UTC
This would be a great feature to allow quick access to play commonly used macros. Even if it were something simple like _Ctl+m+1_ plays the first saved macro.

**Comment by xps** [comment] 2016-06-05 15:48
Thanks for the feedback. I will close as a duplicate of https://github.com/xps/VSTextMacros/issues/7. See the the suggestion I made on that thread can help in the mean time.

**Closed by xps** 2016-06-05 15:48 UTC

**Comment by rusql** [comment] 2016-06-05 16:15
Thank you. Sorry that I missed that this was already suggested.
