### ISSUE TITLE
Copying doesn't work

### ISSUE THREAD

**Issue by phraemer** [xps/VSTextMacros#14] opened 2015-10-29 15:45 UTC
Hi,

If I record a macro where for example I select a word with ctrl+w and then copy it, move and then paste, on subsequent playback it pastes the same text as was copied when recording. Expected is to perform the copy upon every playback.

Thanks,
James

**Comment by xps** [comment] 2015-11-16 14:27
Hi, and thanks for reporting this. However, I can't really reproduce the problem. For me copying and pasting seem to be behaving just as expected. Here's what I've used for testing. Could you please try this and let me know if you get a different result? Maybe it has to do with the Visual Studio version or something.

I started with this text file:

> A
> B
> C
> D

Then I placed my cursor before the `A`. Pressed `Ctrl+Shift+R` to start recording. Then `Shift+Right` to select the `A`, `Ctrl-C` to copy, `Right` to move the cursor out of the selection, `Ctrl-V` to paste. Finally, `Down` and `Left` to move to the next line, and `Ctrl+Shift+R` to end the recording.

I know have `AA` on the first line. I repeat the macro by pressing `Ctrl+Shift+P` 3 times and I end up with:

> AA
> BB
> CC
> DD

**Comment by phraemer** [comment] 2015-11-17 08:45
Hi,

Thanks for getting back to me.
I tried your example and that worked.
Then I tried a more complicated example in some c++ code and sometimes at the point it pasted it resulted in an empty paste. It seems like the bug I am experiencing is somewhat context dependent and not consistent.

I'm using Visual Studio 2013 Update 5
I'll keep trying and see if I can come up with a simple example where it doesn't work.
I'll also check if any other add on is interfering.

thanks,
James

**Comment by ericvana** [comment] 2015-12-15 12:20
Hi,

The Copy recording doesn't seem to work for me as well. 
Also, the above example does not work.
I will try to do some debugging when I have time.

Kind regards,
Eric

**Comment by loicmorvan** [comment] 2016-05-04 15:07
Hi!

Tested by deactivating HTML Copy on my ProPowerTools2015 extension.
And you know what? It works!

Thanks for the tip,
Loïc

**Comment by xps** [comment] 2016-06-05 15:51
I will close this as resolved, as it seems confirmed that the issue was caused by the **Productivity Power Tools 2015** extension. Will reopen if someone can provide a repro not involving the extension.

**Closed by xps** 2016-06-05 15:51 UTC

**Comment by ygoe** [comment] 2017-04-21 19:58
Might be worth adding this info in the README because the PPT extension is fairly common, and it enables all its options by default (and sometimes even on a silent update). Only VS 2017 has this "resolved" by splitting PPT into separate extensions you need to install explicitly.

**Comment by PaltryProgrammer** [comment] 2023-09-12 05:12
greetings kind regards
attached please find GIF demonstrate copy to clipboard then paste fails . please note aforementioned PPT "Copy As HIML" is installed but not enabled .
thank you kindly
![Clipboard Failure](https://github.com/xps/VSTextMacros/assets/48535920/4925e847-2405-42d0-bdd1-ba17f960cb24)
